sampler-app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\API\BookController;
use App\Http\Controllers\API\BookCheckController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [BookController::class, 'indexWeb'])->middleware(['auth'])->name('dashboard');

Route::get('/book-check/{id}', [BookCheckController::class, 'index'])->middleware(['auth'])->name('book-check');

Route::post('/book-check', [BookCheckController::class, 'store'])->middleware(['auth'])->name('book-checked');

require __DIR__.'/auth.php';

sampler-app/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

sampler-app/resources/views/book-checkin.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Books') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form method="POST" action="{{ url('book-check') }}">
                        @csrf
                        <div>
                            <input type="hidden" name="book_id" id="book_id" value="{{ $book->id}}"/>
                            <label class="block font-medium text-sm text-gray-700" for="title">
                                Title
                            </label>
                            <input value="{{ $book->title}}" class="rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 block mt-1 w-full" name="title" id="title" type="text" required="required" autofocus="autofocus">
                        </div>
                        <div class="mt-4">
                            <label class="block font-medium text-sm text-gray-700" for="isbn">
                            ISBN
                        </label>
                            <input value="{{ $book->isbn}}" class="rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 block mt-1 w-full" id="isbn" type="text" name="isbn" required="required" autocomplete="autofocus">
                        </div>
                        <div class="block mt-4">
                            <lable for="action" class="inline-flex items-center">
                                <input value="CHECKIN" id="action" type="radio" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" name="action" required="required">
                                <span class="ml-2 text-sm text-gray-600">Checked In</span>
                            </label>
                            <label for="action" class="inline-flex items-center">
                                <input value="CHECKOUT" id="action" type="radio" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" name="action">
                                <span class="ml-2 text-sm text-gray-600">Checked Out</span>
                            </label>
                        </div>

                        <div class="flex items-center justify-end mt-4">
                            <button type="submit" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150 ml-3">
                                Add
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

sampler-app/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Books') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <!--div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                Test
            </div>
        </div-->
        <div class="md:px-32 py-8 w-full">
            <div class="shadow overflow-hidden rounded border-b border-gray-200">
                <table class="min-w-full bg-white">
                <thead class="bg-gray-800 text-white">
                    <tr>
                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">Title</th>
                    <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">ISBN</th>
                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Status</th>
                    <th class="text-left py-3 px-4 uppercase font-semibold text-sm">Craeted At</td>
                    </tr>
                </thead>
                <tbody class="text-gray-700">
                    @foreach ($books as $book)
                    <tr class="border-b hover:bg-orange-100 bg-gray-100">
                        <td class="p-3 px-5"><a class="hover:text-blue-500" href="{{ url('book-check/'.$book->id) }}">{{ $book->title }}</a></td>
                        <td class="p-3 px-5">{{ $book->isbn }}</td>
                        <td class="p-3 px-5">{{ $book->status }}</td>
                        <td class="p-3 px-5">{{ date('d-m-Y', strtotime($book->created_at)) }}</td>
                        <!--td class="text-left py-3 px-4"><a class="hover:text-blue-500" href="tel:622322662">622322662</a></td-->
                    </tr>
                    @endforeach
                </tbody>
                </table>
            </div>
            </div>
    </div>
</x-app-layout>